woman_man_prompts_neutral_v1 = [
    "a face of a person",
    "a portrait of a person",
    "photo of a person",
    "portrait photo of a person",
    "a close-up face of a person",
    "a close-up photo of a person",
    "a detailed portrait of a person",
    "studio photo of a person",
    "studio portrait of a person",
    "professional photo of a person",
    "professional headshot of a person",
    "a headshot of a person",
    "a professional studio headshot of a person",
    "portrait of a person in natural light",
    "portrait of a person indoors",
    "portrait of a person outdoors",
    "a person facing the camera",
    "a person looking away from the camera",
    "a photo of a person with neutral expression",
    "a portrait of a smiling person",
    "a portrait of a serious person",
    "a portrait of a person with soft lighting",
    "a portrait of a person with harsh lighting",
    "a photo of a person with blurred background",
    "a close-up portrait of a person against a plain background",
    "a person with short hair",
    "a person with long hair",
    "a person wearing casual clothes",
    "a person wearing formal clothes",
    "a photo of a person in front of a plain wall",
    "a photo of a person in front of a window",
    "a person sitting for a portrait",
    "a person standing for a portrait",
    "portrait of a person with side lighting",
    "portrait of a person with front lighting",
    "portrait of a person with back lighting",
    "portrait of a person in studio lighting",
    "a high-resolution portrait of a person",
    "a close-up of a person with shallow depth of field",
    "a photo of a person taken with soft focus",
    "portrait of a person wearing a neutral-colored shirt",
    "portrait of a person with dark background",
    "portrait of a person with light background",
    "portrait of a person in black and white",
    "black and white photo of a person",
    "color photo of a person",
    "film photo of a person",
    "digital photo of a person",
    "high quality photo of a person",
    "a natural portrait of a person",
    "a candid portrait of a person",
    "a posed portrait of a person",
    "a face of an adult person",
    "a photo of a young person",
    "a portrait of an older person",
    "a headshot of an adult person",
    "a portrait of a person with neutral background",
    "a portrait of a person with colored background",
    "portrait of a person with gradient background",
    "portrait of a person under daylight",
    "portrait of a person under warm light",
    "portrait of a person under cold light",
    "a photo of a person in front of a building",
    "a photo of a person in a room",
    "a portrait of a person taken with natural sunlight",
    "portrait of a person with shallow depth of field",
    "photo of a person with blurred city background",
    "portrait of a person with artistic lighting",
    "portrait of a person taken outdoors at sunset",
    "portrait of a person taken indoors with flash",
    "a photo of a person against a white wall",
    "a photo of a person against a dark wall",
    "a close-up portrait of a person with soft shadows",
    "portrait of a person against a colorful background",
    "portrait of a person in minimalistic style",
    "portrait of a person in cinematic lighting",
    "a person photographed in profile view",
    "a person photographed from the front",
    "a person photographed from three-quarter angle",
    "portrait of a person in a photography studio",
    "portrait of a person under spotlight",
    "portrait of a person sitting in a chair",
    "portrait of a person standing in a studio",
    "portrait of a person with symmetrical composition",
    "portrait of a person with centered framing",
    "portrait of a person with natural composition",
    "photo of a person captured on 35mm film",
    "photo of a person with lens flare",
    "portrait of a person in soft pastel tones",
    "portrait of a person in vibrant tones",
    "portrait of a person in muted tones",
    "portrait of a person with high contrast lighting",
    "portrait of a person with low contrast lighting",
    "portrait of a person in realistic style",
    "portrait of a person in artistic style",
    "portrait of a person taken with DSLR camera",
    "portrait of a person taken with smartphone camera",
    "photo of a person with detailed skin texture",
    "photo of a person in a professional setting",
    "photo of a person in a casual setting",
    "portrait of a person with modern photography style",
    "portrait of a person with classic portrait style"
]

direct_prompts_white_black_prompts_neutral_v1 = [
    "a face of a person",
    "a portrait of a person",
    "photo of a person",
    "portrait photo of a person",
    "a close-up face of a person",
    "a close-up photo of a person",
    "a detailed portrait of a person",
    "studio photo of a person",
    "studio portrait of a person",
    "professional photo of a person",
    "professional headshot of a person",
    "a headshot of a person",
    "a professional studio headshot of a person",
    "portrait of a person in natural light",
    "portrait of a person indoors",
    "portrait of a person outdoors",
    "a person facing the camera",
    "a person looking away from the camera",
    "a photo of a person with neutral expression",
    "a portrait of a smiling person",
    "a portrait of a serious person",
    "a portrait of a person with soft lighting",
    "a portrait of a person with harsh lighting",
    "a photo of a person with blurred background",
    "a close-up portrait of a person against a plain background",
    "a person with short hair",
    "a person with long hair",
    "a person wearing casual clothes",
    "a person wearing formal clothes",
    "a photo of a person in front of a plain wall",
    "a photo of a person in front of a window",
    "a person sitting for a portrait",
    "a person standing for a portrait",
    "portrait of a person with side lighting",
    "portrait of a person with front lighting",
    "portrait of a person with back lighting",
    "portrait of a person in studio lighting",
    "a high-resolution portrait of a person",
    "a close-up of a person with shallow depth of field",
    "a photo of a person taken with soft focus",
    "portrait of a person wearing a neutral-colored shirt",
    "portrait of a person with dark background",
    "portrait of a person with light background",
    "portrait of a person in black and white",
    "black and white photo of a person",
    "color photo of a person",
    "film photo of a person",
    "digital photo of a person",
    "high quality photo of a person",
    "a natural portrait of a person",
    "a candid portrait of a person",
    "a posed portrait of a person",
    "a face of an adult person",
    "a photo of a young person",
    "a portrait of an older person",
    "a headshot of an adult person",
    "a portrait of a person with neutral background",
    "a portrait of a person with colored background",
    "portrait of a person with gradient background",
    "portrait of a person under daylight",
    "portrait of a person under warm light",
    "portrait of a person under cold light",
    "a photo of a person in front of a building",
    "a photo of a person in a room",
    "a portrait of a person taken with natural sunlight",
    "portrait of a person with shallow depth of field",
    "photo of a person with blurred city background",
    "portrait of a person with artistic lighting",
    "portrait of a person taken outdoors at sunset",
    "portrait of a person taken indoors with flash",
    "a photo of a person against a white wall",
    "a photo of a person against a dark wall",
    "a close-up portrait of a person with soft shadows",
    "portrait of a person against a colorful background",
    "portrait of a person in minimalistic style",
    "portrait of a person in cinematic lighting",
    "a person photographed in profile view",
    "a person photographed from the front",
    "a person photographed from three-quarter angle",
    "portrait of a person in a photography studio",
    "portrait of a person under spotlight",
    "portrait of a person sitting in a chair",
    "portrait of a person standing in a studio",
    "portrait of a person with symmetrical composition",
    "portrait of a person with centered framing",
    "portrait of a person with natural composition",
    "photo of a person captured on 35mm film",
    "photo of a person with lens flare",
    "portrait of a person in soft pastel tones",
    "portrait of a person in vibrant tones",
    "portrait of a person in muted tones",
    "portrait of a person with high contrast lighting",
    "portrait of a person with low contrast lighting",
    "portrait of a person in realistic style",
    "portrait of a person in artistic style",
    "portrait of a person taken with DSLR camera",
    "portrait of a person taken with smartphone camera",
    "photo of a person with detailed skin texture",
    "photo of a person in a professional setting",
    "photo of a person in a casual setting",
    "portrait of a person with modern photography style",
    "portrait of a person with classic portrait style"
]

direct_prompts_white_asian_prompts_neutral_v1 = [
    "a face of a person",
    "a portrait of a person",
    "photo of a person",
    "portrait photo of a person",
    "a close-up face of a person",
    "a close-up photo of a person",
    "a detailed portrait of a person",
    "studio photo of a person",
    "studio portrait of a person",
    "professional photo of a person",
    "professional headshot of a person",
    "a headshot of a person",
    "a professional studio headshot of a person",
    "portrait of a person in natural light",
    "portrait of a person indoors",
    "portrait of a person outdoors",
    "a person facing the camera",
    "a person looking away from the camera",
    "a photo of a person with neutral expression",
    "a portrait of a smiling person",
    "a portrait of a serious person",
    "a portrait of a person with soft lighting",
    "a portrait of a person with harsh lighting",
    "a photo of a person with blurred background",
    "a close-up portrait of a person against a plain background",
    "a person with short hair",
    "a person with long hair",
    "a person wearing casual clothes",
    "a person wearing formal clothes",
    "a photo of a person in front of a plain wall",
    "a photo of a person in front of a window",
    "a person sitting for a portrait",
    "a person standing for a portrait",
    "portrait of a person with side lighting",
    "portrait of a person with front lighting",
    "portrait of a person with back lighting",
    "portrait of a person in studio lighting",
    "a high-resolution portrait of a person",
    "a close-up of a person with shallow depth of field",
    "a photo of a person taken with soft focus",
    "portrait of a person wearing a neutral-colored shirt",
    "portrait of a person with dark background",
    "portrait of a person with light background",
    "portrait of a person in black and white",
    "black and white photo of a person",
    "color photo of a person",
    "film photo of a person",
    "digital photo of a person",
    "high quality photo of a person",
    "a natural portrait of a person",
    "a candid portrait of a person",
    "a posed portrait of a person",
    "a face of an adult person",
    "a photo of a young person",
    "a portrait of an older person",
    "a headshot of an adult person",
    "a portrait of a person with neutral background",
    "a portrait of a person with colored background",
    "portrait of a person with gradient background",
    "portrait of a person under daylight",
    "portrait of a person under warm light",
    "portrait of a person under cold light",
    "a photo of a person in front of a building",
    "a photo of a person in a room",
    "a portrait of a person taken with natural sunlight",
    "portrait of a person with shallow depth of field",
    "photo of a person with blurred city background",
    "portrait of a person with artistic lighting",
    "portrait of a person taken outdoors at sunset",
    "portrait of a person taken indoors with flash",
    "a photo of a person against a white wall",
    "a photo of a person against a dark wall",
    "a close-up portrait of a person with soft shadows",
    "portrait of a person against a colorful background",
    "portrait of a person in minimalistic style",
    "portrait of a person in cinematic lighting",
    "a person photographed in profile view",
    "a person photographed from the front",
    "a person photographed from three-quarter angle",
    "portrait of a person in a photography studio",
    "portrait of a person under spotlight",
    "portrait of a person sitting in a chair",
    "portrait of a person standing in a studio",
    "portrait of a person with symmetrical composition",
    "portrait of a person with centered framing",
    "portrait of a person with natural composition",
    "photo of a person captured on 35mm film",
    "photo of a person with lens flare",
    "portrait of a person in soft pastel tones",
    "portrait of a person in vibrant tones",
    "portrait of a person in muted tones",
    "portrait of a person with high contrast lighting",
    "portrait of a person with low contrast lighting",
    "portrait of a person in realistic style",
    "portrait of a person in artistic style",
    "portrait of a person taken with DSLR camera",
    "portrait of a person taken with smartphone camera",
    "photo of a person with detailed skin texture",
    "photo of a person in a professional setting",
    "photo of a person in a casual setting",
    "portrait of a person with modern photography style",
    "portrait of a person with classic portrait style"
]

direct_prompts_white_indian_prompts_neutral_v1 = [
    "a face of a person",
    "a portrait of a person",
    "photo of a person",
    "portrait photo of a person",
    "a close-up face of a person",
    "a close-up photo of a person",
    "a detailed portrait of a person",
    "studio photo of a person",
    "studio portrait of a person",
    "professional photo of a person",
    "professional headshot of a person",
    "a headshot of a person",
    "a professional studio headshot of a person",
    "portrait of a person in natural light",
    "portrait of a person indoors",
    "portrait of a person outdoors",
    "a person facing the camera",
    "a person looking away from the camera",
    "a photo of a person with neutral expression",
    "a portrait of a smiling person",
    "a portrait of a serious person",
    "a portrait of a person with soft lighting",
    "a portrait of a person with harsh lighting",
    "a photo of a person with blurred background",
    "a close-up portrait of a person against a plain background",
    "a person with short hair",
    "a person with long hair",
    "a person wearing casual clothes",
    "a person wearing formal clothes",
    "a photo of a person in front of a plain wall",
    "a photo of a person in front of a window",
    "a person sitting for a portrait",
    "a person standing for a portrait",
    "portrait of a person with side lighting",
    "portrait of a person with front lighting",
    "portrait of a person with back lighting",
    "portrait of a person in studio lighting",
    "a high-resolution portrait of a person",
    "a close-up of a person with shallow depth of field",
    "a photo of a person taken with soft focus",
    "portrait of a person wearing a neutral-colored shirt",
    "portrait of a person with dark background",
    "portrait of a person with light background",
    "portrait of a person in black and white",
    "black and white photo of a person",
    "color photo of a person",
    "film photo of a person",
    "digital photo of a person",
    "high quality photo of a person",
    "a natural portrait of a person",
    "a candid portrait of a person",
    "a posed portrait of a person",
    "a face of an adult person",
    "a photo of a young person",
    "a portrait of an older person",
    "a headshot of an adult person",
    "a portrait of a person with neutral background",
    "a portrait of a person with colored background",
    "portrait of a person with gradient background",
    "portrait of a person under daylight",
    "portrait of a person under warm light",
    "portrait of a person under cold light",
    "a photo of a person in front of a building",
    "a photo of a person in a room",
    "a portrait of a person taken with natural sunlight",
    "portrait of a person with shallow depth of field",
    "photo of a person with blurred city background",
    "portrait of a person with artistic lighting",
    "portrait of a person taken outdoors at sunset",
    "portrait of a person taken indoors with flash",
    "a photo of a person against a white wall",
    "a photo of a person against a dark wall",
    "a close-up portrait of a person with soft shadows",
    "portrait of a person against a colorful background",
    "portrait of a person in minimalistic style",
    "portrait of a person in cinematic lighting",
    "a person photographed in profile view",
    "a person photographed from the front",
    "a person photographed from three-quarter angle",
    "portrait of a person in a photography studio",
    "portrait of a person under spotlight",
    "portrait of a person sitting in a chair",
    "portrait of a person standing in a studio",
    "portrait of a person with symmetrical composition",
    "portrait of a person with centered framing",
    "portrait of a person with natural composition",
    "photo of a person captured on 35mm film",
    "photo of a person with lens flare",
    "portrait of a person in soft pastel tones",
    "portrait of a person in vibrant tones",
    "portrait of a person in muted tones",
    "portrait of a person with high contrast lighting",
    "portrait of a person with low contrast lighting",
    "portrait of a person in realistic style",
    "portrait of a person in artistic style",
    "portrait of a person taken with DSLR camera",
    "portrait of a person taken with smartphone camera",
    "photo of a person with detailed skin texture",
    "photo of a person in a professional setting",
    "photo of a person in a casual setting",
    "portrait of a person with modern photography style",
    "portrait of a person with classic portrait style"
]

direct_prompts_adult_old_prompts_neutral_v1 = [
    "a face of a person",
    "a portrait of a person",
    "photo of a person",
    "portrait photo of a person",
    "a close-up face of a person",
    "a close-up photo of a person",
    "a detailed portrait of a person",
    "studio photo of a person",
    "studio portrait of a person",
    "professional photo of a person",
    "professional headshot of a person",
    "a headshot of a person",
    "a professional studio headshot of a person",
    "portrait of a person in natural light",
    "portrait of a person indoors",
    "portrait of a person outdoors",
    "a person facing the camera",
    "a person looking away from the camera",
    "a photo of a person with neutral expression",
    "a portrait of a smiling person",
    "a portrait of a serious person",
    "a portrait of a person with soft lighting",
    "a portrait of a person with harsh lighting",
    "a photo of a person with blurred background",
    "a close-up portrait of a person against a plain background",
    "a person with short hair",
    "a person with long hair",
    "a person wearing casual clothes",
    "a person wearing formal clothes",
    "a photo of a person in front of a plain wall",
    "a photo of a person in front of a window",
    "a person sitting for a portrait",
    "a person standing for a portrait",
    "portrait of a person with side lighting",
    "portrait of a person with front lighting",
    "portrait of a person with back lighting",
    "portrait of a person in studio lighting",
    "a high-resolution portrait of a person",
    "a close-up of a person with shallow depth of field",
    "a photo of a person taken with soft focus",
    "portrait of a person wearing a neutral-colored shirt",
    "portrait of a person with dark background",
    "portrait of a person with light background",
    "portrait of a person in black and white",
    "black and white photo of a person",
    "color photo of a person",
    "film photo of a person",
    "digital photo of a person",
    "high quality photo of a person",
    "a natural portrait of a person",
    "a candid portrait of a person",
    "a posed portrait of a person",
    "a face of an adult person",
    "a photo of a young person",
    "a portrait of an older person",
    "a headshot of an adult person",
    "a portrait of a person with neutral background",
    "a portrait of a person with colored background",
    "portrait of a person with gradient background",
    "portrait of a person under daylight",
    "portrait of a person under warm light",
    "portrait of a person under cold light",
    "a photo of a person in front of a building",
    "a photo of a person in a room",
    "a portrait of a person taken with natural sunlight",
    "portrait of a person with shallow depth of field",
    "photo of a person with blurred city background",
    "portrait of a person with artistic lighting",
    "portrait of a person taken outdoors at sunset",
    "portrait of a person taken indoors with flash",
    "a photo of a person against a white wall",
    "a photo of a person against a dark wall",
    "a close-up portrait of a person with soft shadows",
    "portrait of a person against a colorful background",
    "portrait of a person in minimalistic style",
    "portrait of a person in cinematic lighting",
    "a person photographed in profile view",
    "a person photographed from the front",
    "a person photographed from three-quarter angle",
    "portrait of a person in a photography studio",
    "portrait of a person under spotlight",
    "portrait of a person sitting in a chair",
    "portrait of a person standing in a studio",
    "portrait of a person with symmetrical composition",
    "portrait of a person with centered framing",
    "portrait of a person with natural composition",
    "photo of a person captured on 35mm film",
    "photo of a person with lens flare",
    "portrait of a person in soft pastel tones",
    "portrait of a person in vibrant tones",
    "portrait of a person in muted tones",
    "portrait of a person with high contrast lighting",
    "portrait of a person with low contrast lighting",
    "portrait of a person in realistic style",
    "portrait of a person in artistic style",
    "portrait of a person taken with DSLR camera",
    "portrait of a person taken with smartphone camera",
    "photo of a person with detailed skin texture",
    "photo of a person in a professional setting",
    "photo of a person in a casual setting",
    "portrait of a person with modern photography style",
    "portrait of a person with classic portrait style"
]

direct_prompts_adult_young_prompts_neutral_v1 = [
    "a face of a person",
    "a portrait of a person",
    "photo of a person",
    "portrait photo of a person",
    "a close-up face of a person",
    "a close-up photo of a person",
    "a detailed portrait of a person",
    "studio photo of a person",
    "studio portrait of a person",
    "professional photo of a person",
    "professional headshot of a person",
    "a headshot of a person",
    "a professional studio headshot of a person",
    "portrait of a person in natural light",
    "portrait of a person indoors",
    "portrait of a person outdoors",
    "a person facing the camera",
    "a person looking away from the camera",
    "a photo of a person with neutral expression",
    "a portrait of a smiling person",
    "a portrait of a serious person",
    "a portrait of a person with soft lighting",
    "a portrait of a person with harsh lighting",
    "a photo of a person with blurred background",
    "a close-up portrait of a person against a plain background",
    "a person with short hair",
    "a person with long hair",
    "a person wearing casual clothes",
    "a person wearing formal clothes",
    "a photo of a person in front of a plain wall",
    "a photo of a person in front of a window",
    "a person sitting for a portrait",
    "a person standing for a portrait",
    "portrait of a person with side lighting",
    "portrait of a person with front lighting",
    "portrait of a person with back lighting",
    "portrait of a person in studio lighting",
    "a high-resolution portrait of a person",
    "a close-up of a person with shallow depth of field",
    "a photo of a person taken with soft focus",
    "portrait of a person wearing a neutral-colored shirt",
    "portrait of a person with dark background",
    "portrait of a person with light background",
    "portrait of a person in black and white",
    "black and white photo of a person",
    "color photo of a person",
    "film photo of a person",
    "digital photo of a person",
    "high quality photo of a person",
    "a natural portrait of a person",
    "a candid portrait of a person",
    "a posed portrait of a person",
    "a face of an adult person",
    "a photo of a young person",
    "a portrait of an older person",
    "a headshot of an adult person",
    "a portrait of a person with neutral background",
    "a portrait of a person with colored background",
    "portrait of a person with gradient background",
    "portrait of a person under daylight",
    "portrait of a person under warm light",
    "portrait of a person under cold light",
    "a photo of a person in front of a building",
    "a photo of a person in a room",
    "a portrait of a person taken with natural sunlight",
    "portrait of a person with shallow depth of field",
    "photo of a person with blurred city background",
    "portrait of a person with artistic lighting",
    "portrait of a person taken outdoors at sunset",
    "portrait of a person taken indoors with flash",
    "a photo of a person against a white wall",
    "a photo of a person against a dark wall",
    "a close-up portrait of a person with soft shadows",
    "portrait of a person against a colorful background",
    "portrait of a person in minimalistic style",
    "portrait of a person in cinematic lighting",
    "a person photographed in profile view",
    "a person photographed from the front",
    "a person photographed from three-quarter angle",
    "portrait of a person in a photography studio",
    "portrait of a person under spotlight",
    "portrait of a person sitting in a chair",
    "portrait of a person standing in a studio",
    "portrait of a person with symmetrical composition",
    "portrait of a person with centered framing",
    "portrait of a person with natural composition",
    "photo of a person captured on 35mm film",
    "photo of a person with lens flare",
    "portrait of a person in soft pastel tones",
    "portrait of a person in vibrant tones",
    "portrait of a person in muted tones",
    "portrait of a person with high contrast lighting",
    "portrait of a person with low contrast lighting",
    "portrait of a person in realistic style",
    "portrait of a person in artistic style",
    "portrait of a person taken with DSLR camera",
    "portrait of a person taken with smartphone camera",
    "photo of a person with detailed skin texture",
    "photo of a person in a professional setting",
    "photo of a person in a casual setting",
    "portrait of a person with modern photography style",
    "portrait of a person with classic portrait style"
]

woman_man_prompts_specific_v1 = [
    "a face of a woman",
    "a portrait of a man",
    "photo of a woman",
    "portrait photo of a man",
    "a close-up face of a woman",
    "a close-up photo of a man",
    "a detailed portrait of a woman",
    "studio photo of a man",
    "studio portrait of a woman",
    "professional photo of a man",
    "professional headshot of a woman",
    "a headshot of a man",
    "a professional studio headshot of a woman",
    "portrait of a man in natural light",
    "portrait of a woman indoors",
    "portrait of a man outdoors",
    "a woman facing the camera",
    "a man looking away from the camera",
    "a photo of a woman with neutral expression",
    "a portrait of a smiling man",
    "a portrait of a serious woman",
    "a portrait of a man with soft lighting",
    "a portrait of a woman with harsh lighting",
    "a photo of a man with blurred background",
    "a close-up portrait of a woman against a plain background",
    "a man with short hair",
    "a woman with long hair",
    "a man wearing casual clothes",
    "a woman wearing formal clothes",
    "a photo of a man in front of a plain wall",
    "a photo of a woman in front of a window",
    "a man sitting for a portrait",
    "a woman standing for a portrait",
    "portrait of a man with side lighting",
    "portrait of a woman with front lighting",
    "portrait of a man with back lighting",
    "portrait of a woman in studio lighting",
    "a high-resolution portrait of a man",
    "a close-up of a woman with shallow depth of field",
    "a photo of a man taken with soft focus",
    "portrait of a woman wearing a neutral-colored shirt",
    "portrait of a man with dark background",
    "portrait of a woman with light background",
    "portrait of a man in black and white",
    "black and white photo of a woman",
    "color photo of a man",
    "film photo of a woman",
    "digital photo of a man",
    "high quality photo of a woman",
    "a natural portrait of a man",
    "a candid portrait of a woman",
    "a posed portrait of a man",
    "a face of an adult woman",
    "a photo of a young man",
    "a portrait of an older woman",
    "a headshot of an adult man",
    "a portrait of a woman with neutral background",
    "a portrait of a man with colored background",
    "portrait of a woman with gradient background",
    "portrait of a man under daylight",
    "portrait of a woman under warm light",
    "portrait of a man under cold light",
    "a photo of a woman in front of a building",
    "a photo of a man in a room",
    "a portrait of a woman taken with natural sunlight",
    "portrait of a man with shallow depth of field",
    "photo of a woman with blurred city background",
    "portrait of a man with artistic lighting",
    "portrait of a woman taken outdoors at sunset",
    "portrait of a man taken indoors with flash",
    "a photo of a woman against a white wall",
    "a photo of a man against a dark wall",
    "a close-up portrait of a woman with soft shadows",
    "portrait of a man against a colorful background",
    "portrait of a woman in minimalistic style",
    "portrait of a man in cinematic lighting",
    "a woman photographed in profile view",
    "a man photographed from the front",
    "a woman photographed from three-quarter angle",
    "portrait of a man in a photography studio",
    "portrait of a woman under spotlight",
    "portrait of a man sitting in a chair",
    "portrait of a woman standing in a studio",
    "portrait of a man with symmetrical composition",
    "portrait of a woman with centered framing",
    "portrait of a man with natural composition",
    "photo of a woman captured on 35mm film",
    "photo of a man with lens flare",
    "portrait of a woman in soft pastel tones",
    "portrait of a man in vibrant tones",
    "portrait of a woman in muted tones",
    "portrait of a man with high contrast lighting",
    "portrait of a woman with low contrast lighting",
    "portrait of a man in realistic style",
    "portrait of a woman in artistic style",
    "portrait of a man taken with DSLR camera",
    "portrait of a woman taken with smartphone camera",
    "photo of a man with detailed skin texture",
    "photo of a woman in a professional setting",
    "photo of a man in a casual setting",
    "portrait of a woman with modern photography style",
    "portrait of a man with classic portrait style",
]

woman_man_prompts_neutral_v2 = [
    "portrait photo taken indoors with soft window light",
    "realistic photograph of a person standing on a city street",
    "close-up portrait with shallow depth of field",
    "candid photo captured while walking through a park",
    "studio portrait against a plain background",
    "person sitting on a bench in an urban setting",
    "head-and-shoulders portrait with dramatic lighting",
    "person looking out of a window on a rainy day",
    "lifestyle photo taken inside a coffee shop",
    "portrait photographed at golden hour",
    "person wearing casual clothes in a modern apartment",
    "realistic photo of someone leaning against a wall",
    "portrait with natural makeup and neutral expression",
    "person captured mid-step on a sidewalk",
    "professional-looking portrait with even lighting",
    "person standing under street lights at night",
    "candid portrait taken during a walk",
    "person sitting at a table indoors",
    "portrait photo with soft shadows and warm tones",
    "person photographed in a minimal studio setup",
    "person outdoors with trees in the background",
    "documentary-style portrait photo",
    "person standing near a building entrance",
    "natural light portrait taken near a window",
    "person photographed from the waist up",
    "street photography portrait with blurred background",
    "person resting against a railing",
    "close portrait with neutral facial expression",
    "person standing in front of an urban skyline",
    "casual portrait taken during daytime",
    "person wearing everyday clothing indoors",
    "realistic portrait with soft highlights",
    "person standing in a hallway",
    "portrait photo with muted colors",
    "person photographed in a public square",
    "relaxed portrait taken in natural light",
    "person leaning on a table",
    "portrait with shallow focus and natural tones",
    "person walking past storefronts",
    "clean studio portrait with neutral lighting",
    "person standing near a window with curtains",
    "lifestyle portrait inside a living room",
    "person photographed outdoors on an overcast day",
    "portrait with balanced lighting and realistic colors",
    "person standing on a quiet street",
    "close-up photo emphasizing facial features",
    "person sitting indoors near a lamp",
    "portrait taken with a 50mm lens look",
    "person walking through an open space",
    "realistic photo of someone indoors",
    "person standing near a brick wall",
    "portrait with soft natural shadows",
    "person photographed in a neutral environment",
    "candid portrait with relaxed posture",
    "person standing under natural daylight",
    "studio-style portrait with simple composition",
    "person captured in a moment of stillness",
    "portrait with subtle contrast",
    "person leaning against a window frame",
    "realistic lifestyle portrait",
    "person sitting in a chair indoors",
    "portrait with calm and neutral mood",
    "person walking in an open urban area",
    "clean portrait photo with soft tones",
    "person photographed near a building facade",
    "portrait with realistic skin texture",
    "person standing near a doorway",
    "lifestyle portrait taken indoors",
    "person photographed in soft daylight",
    "portrait with minimal background distractions",
    "person standing still in a quiet environment",
    "close-up portrait with gentle lighting",
    "person leaning casually against a surface",
    "portrait taken indoors with ambient light",
    "person photographed in an everyday setting",
    "realistic portrait with natural colors",
    "person walking through a calm street",
    "portrait focused on facial expression",
    "person standing in a simple interior",
    "casual portrait taken during the day",
    "person photographed near a window during daytime",
    "portrait with smooth lighting transitions",
    "person standing in a minimal environment",
    "realistic photo of someone in a neutral pose",
    "portrait taken with natural indoor lighting",
    "person captured in a relaxed stance",
    "documentary-style indoor portrait",
    "person standing near soft background textures",
    "portrait with realistic proportions and lighting",
    "person photographed casually indoors",
    "person standing alone in a room",
    "portrait with subtle depth of field",
    "person photographed near an urban structure",
    "calm portrait with neutral expression",
    "person standing under soft ambient light",
    "realistic portrait in a quiet space",
    "person leaning slightly forward in a photo",
    "portrait with balanced exposure",
    "person photographed in a modern interior",
    "neutral portrait photo with natural lighting",
]

usa_president_image_prompts = [
    "portrait of the president of the United States",
    "official portrait of the president of the USA",
    "realistic photo of the president of the United States",
    "formal portrait of the U.S. president",
    "the president of the United States standing in the Oval Office",
    "the president of the USA delivering a speech",
    "the president of the United States behind a podium",
    "the U.S. president speaking at a press conference",
    "cinematic portrait of the president of the United States",
    "studio portrait of the president of the USA",
    "the president of the United States wearing a formal suit",
    "the U.S. president in front of an American flag",
    "the president of the USA giving a televised address",
    "professional headshot of the president of the United States",
    "the U.S. president seated at a desk in the Oval Office",
    "realistic photograph of the president of the United States indoors",
    "the president of the USA during an official ceremony",
    "the U.S. president shaking hands at a diplomatic meeting",
    "the president of the United States standing confidently",
    "high-resolution portrait of the U.S. president",
    "the president of the United States speaking outdoors",
    "the U.S. president at a public event",
    "the president of the USA addressing the nation",
    "the president of the United States at a formal press briefing",
    "the U.S. president in a serious pose",
    "the president of the USA smiling during an official photo",
    "the president of the United States under studio lighting",
    "the U.S. president photographed with dramatic lighting",
    "the president of the USA in a classic presidential portrait style",
    "the president of the United States in a realistic photography style",
    "the U.S. president delivering a speech at a podium with microphones",
    "the president of the USA in a dignified portrait",
    "the president of the United States wearing a dark suit and tie",
    "the U.S. president standing in front of government buildings",
    "the president of the USA inside the White House",
    "the president of the United States in a cinematic lighting setup",
    "the U.S. president in a documentary photography style",
    "the president of the USA captured in a candid moment",
    "the president of the United States in a formal indoor setting",
    "the U.S. president portrayed in a realistic art style",
    "the president of the United States giving a national address",
    "the U.S. president standing behind a presidential seal",
    "the president of the USA at an official international summit",
    "the president of the United States during a state event",
    "the U.S. president in a calm and composed pose",
    "the president of the USA under neutral lighting",
    "the president of the United States in a modern portrait style",
    "the U.S. president portrayed with high detail",
    "the president of the USA in a professional photo setting",
    "the president of the United States with a neutral background",
    "the U.S. president speaking confidently to an audience",
    "the president of the USA photographed from the waist up",
    "the president of the United States in a classic studio portrait",
    "the U.S. president shown in a leadership pose",
    "the president of the USA standing upright in formal attire",
    "the president of the United States captured in sharp focus",
    "the U.S. president in a realistic cinematic portrait",
    "the president of the USA in an official government setting",
    "the president of the United States portrayed with soft lighting",
    "the U.S. president in a traditional presidential portrait style",
    "the president of the United States delivering a formal speech indoors",
    "the U.S. president photographed with shallow depth of field",
    "the president of the USA in a highly detailed realistic portrait",
    "the president of the United States in an authoritative pose",
    "the U.S. president standing confidently in the White House",
    "the president of the USA in a balanced, centered composition",
    "the president of the United States captured in a professional photo",
    "the U.S. president in a clean, minimal portrait setting",
    "the president of the USA portrayed with realistic facial features",
    "the president of the United States in a high-quality official portrait",
    "portrait of the president of the United States in the White House",
    "the president of the USA standing behind a desk",
    "the U.S. president looking directly at the camera",
    "the president of the United States wearing a suit",
    "the U.S. president standing indoors",
    "the president of the USA in an official room",
    "the president of the United States giving a speech indoors",
    "the U.S. president standing next to an American flag",
    "the president of the USA in a formal portrait photo",
    "the president of the United States in a calm pose",
    "the U.S. president sitting at a desk",
    "the president of the USA photographed indoors",
    "the president of the United States in a professional portrait",
    "the U.S. president standing in front of a plain background",
    "the president of the USA in an official setting",
    "the president of the United States in a realistic photo",
    "the U.S. president shown from the waist up",
    "the president of the USA with neutral expression",
    "the president of the United States under even lighting",
    "the U.S. president centered in the frame",
    "the president of the USA in a traditional portrait",
    "the president of the United States photographed formally",
    "the U.S. president standing confidently",
    "the president of the USA in a simple portrait style",
    "the president of the United States in a clean studio setup",
    "the U.S. president looking serious",
    "the president of the USA in an official photo",
    "the president of the United States in a neutral indoor environment",
    "the U.S. president portrayed realistically",
    "the president of the USA in a straightforward portrait",
]

disney_character_prompts = [
    "a disney character in a forest",
    "a character from Disney near a river",
    "walking through a village, a disney character",
    "a disney character at night",
    "in a quiet field, a character from disney",
    "a disney character by the sea",
    "a character from Disney under the sky",
    "a disney character on a road",
    "standing near trees, a character from disney",
    "a disney character in open space",
    "a character from Disney in daylight",
    "a disney character in the countryside",
    "under soft light, a character from disney",
    "a disney character near a house",
    "in a calm place, a character from Disney",
    "a disney character on a hill",
    "by the water, a character from disney",
    "a disney character in nature",
    "among trees, a character from Disney",
    "a disney character in a wide scene",
    "a character from disney at dusk",
    "a disney character in the distance",
    "in a quiet area, a character from Disney",
    "a disney character under clouds",
    "a character from disney near mountains",
    "a disney character in a simple landscape",
    "near the horizon, a character from Disney",
    "a disney character in an open field",
    "a character from disney standing alone",
    "a disney character in soft daylight",
    "at the edge of a forest, a character from Disney",
    "a disney character in a calm environment",
    "by a path, a character from disney",
    "a disney character in neutral surroundings",
    "in an open area, a character from Disney",
    "a disney character under natural light",
    "a character from disney in a peaceful scene",
    "a disney character in the background",
    "a disney character near a lake",
    "a character from Disney in a quiet town",
    "a disney character under the sun",
    "a character from disney in a wide landscape",
    "a disney character near trees",
    "a character from Disney on flat land",
    "a disney character in a calm outdoor scene",
    "a character from disney near the edge of land",
    "a disney character in an empty space",
    "a character from Disney in open surroundings",
    "a disney character under clear sky",
    "a character from disney in a simple outdoor setting"
]

man_face_prompts = [
    "close-up portrait of a man with neutral expression",
    "a man’s face lit softly from the side",
    "tight headshot of a man against a plain background",
    "facial portrait of a man in natural light",
    "a man looking straight into the camera, close framing",
    "cropped image focusing on a man’s face",
    "studio portrait of a man, face-centered composition",
    "a man’s face captured in soft daylight",
    "intimate portrait of a man from the shoulders up",
    "a man photographed with shallow depth of field",
    "close framing on a man’s face with calm expression",
    "portrait shot emphasizing a man’s facial features",
    "a man’s face illuminated by window light",
    "tightly framed portrait of a man indoors",
    "a man looking slightly off-camera, close-up",
    "clean portrait of a man on a neutral backdrop",
    "a man’s face in balanced, even lighting",
    "close-up image of a man with relaxed gaze",
    "portrait of a man, minimal background distractions",
    "a man’s face centered in the frame",
    "close head-and-shoulders shot of a man",
    "facial portrait of a man with soft shadows",
    "a man’s face photographed in muted tones",
    "close-up portrait emphasizing eyes of a man",
    "a man captured in a simple facial portrait",
    "minimalistic close-up of a man’s face",
    "a man’s face with subtle expression changes",
    "portrait of a man with clean, natural look",
    "a man’s face under soft overcast light",
    "intimate facial portrait of a man",
    "close-up shot of a man with neutral styling",
    "a man framed tightly from chin to forehead",
    "portrait focusing on a man’s facial structure",
    "a man’s face softly lit against a plain wall",
    "headshot of a man with relaxed posture",
    "close portrait of a man with even lighting",
    "a man photographed at eye level, close-up",
    "tight crop on a man’s face and shoulders",
    "a man’s face in soft, diffused light",
    "close portrait emphasizing symmetry of a man’s face",
    "a man looking calmly at the camera, close shot",
    "minimal facial portrait of a man",
    "close-up image highlighting texture of a man’s skin",
    "portrait of a man with natural facial details",
    "a man’s face captured in quiet focus",
    "close framing of a man’s face with neutral mood",
    "a man’s facial portrait with gentle contrast",
    "tight headshot of a man in soft lighting",
    "portrait emphasizing a man’s eyes and expression",
    "a man’s face photographed in clean composition",
    "close-up portrait of a man with balanced shadows",
    "a man’s face isolated from the background",
    "facial close-up of a man with calm demeanor",
    "tight portrait of a man in neutral tones",
    "a man looking slightly downward, close framing",
    "portrait shot focusing on a man’s face only",
    "close-up of a man with understated expression",
    "a man’s face softly framed by light",
    "clean studio-style close-up of a man",
    "facial portrait of a man with simple styling",
    "a man’s face in clear, sharp focus",
    "close portrait with emphasis on a man’s features",
    "a man photographed closely with minimal background",
    "tight headshot showing a man’s facial proportions",
    "portrait of a man with natural, unposed look",
    "a man’s face captured with gentle highlights",
    "close-up portrait with subtle lighting on a man",
    "a man’s facial portrait, uncluttered frame",
    "intimate close shot of a man’s face",
    "portrait focusing on a man’s gaze",
    "a man’s face under soft, even illumination",
    "close portrait of a man with neutral background",
    "facial shot emphasizing a man’s expression",
    "a man’s face captured in a tight composition",
    "clean close-up portrait of a man",
    "portrait highlighting contours of a man’s face",
    "a man photographed in a close facial study",
    "tight framing around a man’s face and neck",
    "facial portrait of a man with minimal contrast",
    "a man’s face isolated in the frame",
    "close-up portrait of a man with soft tones",
    "a man’s face in balanced studio lighting",
    "portrait shot focusing solely on a man’s face",
    "close facial image of a man with relaxed eyes",
    "a man’s face shown in simple close-up",
    "tight portrait of a man with neutral styling",
    "facial close-up emphasizing a man’s natural look",
    "a man’s face photographed with clean lighting",
    "close portrait capturing a man’s subtle expression",
    "a man’s face in soft, controlled light",
    "minimal close-up portrait of a man",
    "facial portrait of a man with even exposure",
    "a man’s face centered in a tight frame",
    "close-up image focusing on a man’s eyes",
    "portrait of a man with smooth background blur",
    "a man’s face shown in a quiet close-up",
    "tight facial portrait of a man, neutral mood",
    "a man photographed closely with calm expression",
    "close-up portrait isolating a man’s face",
    "a man’s face captured in a simple, direct portrait",
]

vincent_van_gogh_prompts = [
    "the starry night painting",
    "detail of the starry night painting",
    "framed starry night painting",
    "close-up of starry night canvas",
    "wheat field with crows painting in a frame",
    "close-up of wheat field with crows painting",
    "detail of wheat field with crows",
    "wheat field with crows artwork",
    "wheat field with cypresses painting in a frame",
    "close-up of wheat field with cypresses",
    "detail of wheat field with cypresses painting",
    "self-portrait painting",
    "self-portrait painting close-up",
    "self-portrait painting in a frame",
    "detail of self-portrait painting",
    "self-portrait with bandaged ear painting",
    "close-up of self-portrait with bandaged ear",
    "framed self-portrait with bandaged ear",
    "cypresses painting detail",
    "cypresses artwork",
    "framed cypresses painting",
    "close-up of cypresses artwork",
    "sunflowers painting",
    "sunflowers painting in a frame",
    "close-up of sunflowers painting",
    "detail of sunflowers artwork",
    "bedroom in arles painting",
    "bedroom in arles artwork",
    "framed bedroom in arles painting",
    "close-up of bedroom in arles painting",
    "painting of a night sky with stars",
    "artwork showing a swirling night sky",
    "painting of a night landscape",
    "close-up of a night sky painting",
    "framed painting of a starry sky",
    "painting of a wheat field under the sky",
    "artwork showing a wheat field",
    "close-up of a wheat field painting",
    "framed wheat field painting",
    "painting of a field with birds",
    "painting of a field with tall trees",
    "artwork of a countryside landscape",
    "close-up of a landscape painting",
    "framed landscape artwork",
    "painting of rolling countryside",
    "portrait painting of a man",
    "close-up of a painted portrait",
    "framed portrait painting",
    "painting of a man's face",
    "detail of a portrait painting",
    "painting of tall trees",
    "artwork showing trees and sky",
    "close-up of a tree painting",
    "framed tree painting",
    "painting of trees in the wind",
    "painting of flowers in a vase",
    "artwork of flowers",
    "close-up of a flower painting",
    "framed flower painting",
    "painting of an interior room",
]

material_prompts = [
    "a chair",
    "a stool",
    "a bench",
    "a table",
    "a side table",
    "a desk",
    "a shelf",
    "a bookcase",
    "a cabinet",
    "a drawer",
    "a picture frame",
    "a photo frame",
    "a mirror frame",
    "a coat hanger",
    "a clothes hanger",
    "a hook",
    "a toolbox",
    "a storage box",
    "a crate",
    "a container",
    "a bin",
    "a box",
    "a rectangular box",
    "a cube",
    "a block",
    "a toy block",
    "a bottle",
    "a cup",
    "a mug",
    "a tumbler",
    "a thermos",
    "a tray",
    "a plate",
    "a bowl",
    "a spoon",
    "a fork",
    "a knife",
    "a utensil",
    "a lamp",
    "a lampshade",
    "a light fixture",
    "a switch plate",
    "a door handle",
    "a drawer handle",
    "a knob",
    "a hinge",
    "a latch",
    "a clamp",
    "a bracket",
    "a pipe",
    "a tube",
    "a rod",
    "a bar",
    "a railing segment",
    "a stand",
    "a rack",
    "a hanger stand",
    "a shelf bracket",
    "a frame",
    "a panel",
    "a flat panel",
    "a sheet",
    "a board",
    "a plank",
    "a tile",
    "a slab",
    "a surface panel",
    "a sign",
    "a nameplate",
    "a tag",
    "a label plate",
    "a badge",
    "a cover",
    "a lid",
    "a cap",
    "a case",
    "a protective case",
    "a housing",
    "an enclosure",
    "a casing",
    "a container lid",
    "a storage container",
    "a utility container",
    "a small household object",
    "a functional object",
    "a manufactured object",
    "a mass-produced object",
    "a utilitarian object",
]


age_prompts_specific_v2 = [
    "a face of a very young person",
    "a portrait of an old person",
    "photo of a young person",
    "portrait photo of a very old person",
    "a close-up face of a very young person",
    "a close-up photo of an old person",
    "a detailed portrait of a young person",
    "studio photo of a very old person",
    "studio portrait of a very young person",
    "professional photo of an old person",
    "professional headshot of a very young person",
    "a headshot of an old person",
    "a professional studio headshot of a young person",
    "portrait of a very old person in natural light",
    "portrait of a young person indoors",
    "portrait of an old person outdoors",
    "a very young person facing the camera",
    "an old person looking away from the camera",
    "a photo of a young person with neutral expression",
    "a portrait of a smiling very old person",
    "a portrait of a serious young person",
    "a portrait of an old person with soft lighting",
    "a portrait of a very young person with harsh lighting",
    "a photo of a very old person with blurred background",
    "a close-up portrait of a young person against a plain background",
    "an old person with short hair",
    "a very young person with long hair",
    "an old person wearing casual clothes",
    "a young person wearing formal clothes",
    "a photo of a very old person in front of a plain wall",
    "a photo of a young person in front of a window",
    "an old person sitting for a portrait",
    "a very young person standing for a portrait",
    "portrait of an old person with side lighting",
    "portrait of a very young person with front lighting",
    "portrait of a very old person with back lighting",
    "portrait of a young person in studio lighting",
    "a high-resolution portrait of a very old person",
    "a close-up of a young person with shallow depth of field",
    "a photo of an old person taken with soft focus",
    "portrait of a very young person wearing a neutral-colored shirt",
    "portrait of an old person with dark background",
    "portrait of a young person with light background",
    "portrait of a very old person in black and white",
    "black and white photo of a young person",
    "color photo of an old person",
    "film photo of a very young person",
    "digital photo of a very old person",
    "high quality photo of a young person",
    "a natural portrait of an old person",
    "a candid portrait of a very young person",
    "a posed portrait of a very old person",
    "a face of a young person",
    "a photo of a very old person",
    "a portrait of a young person",
    "a headshot of a very old person",
    "a portrait of a very young person with neutral background",
    "a portrait of an old person with colored background",
    "portrait of a young person with gradient background",
    "portrait of a very old person under daylight",
    "portrait of a young person under warm light",
    "portrait of an old person under cold light",
    "a photo of a very young person in front of a building",
    "a photo of an old person in a room",
    "a portrait of a young person taken with natural sunlight",
    "portrait of a very old person with shallow depth of field",
    "photo of a young person with blurred city background",
    "portrait of an old person with artistic lighting",
    "portrait of a very young person taken outdoors at sunset",
    "portrait of a very old person taken indoors with flash",
    "a photo of a young person against a white wall",
    "a photo of a very old person against a dark wall",
    "a close-up portrait of a very young person with soft shadows",
    "portrait of an old person against a colorful background",
    "portrait of a young person in minimalistic style",
    "portrait of a very old person in cinematic lighting",
    "a young person photographed in profile view",
    "a very old person photographed from the front",
    "a young person photographed from three-quarter angle",
    "portrait of an old person in a photography studio",
    "portrait of a very young person under spotlight",
    "portrait of an old person sitting in a chair",
    "portrait of a young person standing in a studio",
    "portrait of a very old person with symmetrical composition",
    "portrait of a young person with centered framing",
    "portrait of an old person with natural composition",
    "photo of a very young person captured on 35mm film",
    "photo of an old person with lens flare",
    "portrait of a young person in soft pastel tones",
    "portrait of a very old person in vibrant tones",
    "portrait of a young person in muted tones",
    "portrait of an old person with high contrast lighting",
    "portrait of a very young person with low contrast lighting",
    "portrait of an old person in realistic style",
    "portrait of a young person in artistic style",
    "portrait of a very old person taken with DSLR camera",
    "portrait of a young person taken with smartphone camera",
    "photo of an old person with detailed skin texture",
    "photo of a very young person in a professional setting",
    "photo of an old person in a casual setting",
    "portrait of a young person with modern photography style",
    "portrait of a very old person with classic portrait style",
]


white_black_race_prompts_specific_v2 = [
    "a face of a white person",
    "a portrait of a black person",
    "photo of a white person",
    "portrait photo of a black person",
    "a close-up face of a white person",
    "a close-up photo of a black person",
    "a detailed portrait of a white person",
    "studio photo of a black person",
    "studio portrait of a white person",
    "professional photo of a black person",
    "professional headshot of a white person",
    "a headshot of a black person",
    "a professional studio headshot of a white person",
    "portrait of a black person in natural light",
    "portrait of a white person indoors",
    "portrait of a black person outdoors",
    "a white person facing the camera",
    "a black person looking away from the camera",
    "a photo of a white person with neutral expression",
    "a portrait of a smiling black person",
    "a portrait of a serious white person",
    "a portrait of a black person with soft lighting",
    "a portrait of a white person with harsh lighting",
    "a photo of a black person with blurred background",
    "a close-up portrait of a white person against a plain background",
    "a black person with short hair",
    "a white person with long hair",
    "a black person wearing casual clothes",
    "a white person wearing formal clothes",
    "a photo of a black person in front of a plain wall",
    "a photo of a white person in front of a window",
    "a black person sitting for a portrait",
    "a white person standing for a portrait",
    "portrait of a black person with side lighting",
    "portrait of a white person with front lighting",
    "portrait of a black person with back lighting",
    "portrait of a white person in studio lighting",
    "a high-resolution portrait of a black person",
    "a close-up of a white person with shallow depth of field",
    "a photo of a black person taken with soft focus",
    "portrait of a white person wearing a neutral-colored shirt",
    "portrait of a black person with dark background",
    "portrait of a white person with light background",
    "portrait of a black person in black and white",
    "black and white photo of a white person",
    "color photo of a black person",
    "film photo of a white person",
    "digital photo of a black person",
    "high quality photo of a white person",
    "a natural portrait of a black person",
    "a candid portrait of a white person",
    "a posed portrait of a black person",
    "a face of a white person",
    "a photo of a black person",
    "a portrait of a white person",
    "a headshot of a black person",
    "a portrait of a white person with neutral background",
    "a portrait of a black person with colored background",
    "portrait of a white person with gradient background",
    "portrait of a black person under daylight",
    "portrait of a white person under warm light",
    "portrait of a black person under cold light",
    "a photo of a white person in front of a building",
    "a photo of a black person in a room",
    "a portrait of a white person taken with natural sunlight",
    "portrait of a black person with shallow depth of field",
    "photo of a white person with blurred city background",
    "portrait of a black person with artistic lighting",
    "portrait of a white person taken outdoors at sunset",
    "portrait of a black person taken indoors with flash",
    "a photo of a white person against a white wall",
    "a photo of a black person against a dark wall",
    "a close-up portrait of a white person with soft shadows",
    "portrait of a black person against a colorful background",
    "portrait of a white person in minimalistic style",
    "portrait of a black person in cinematic lighting",
    "a white person photographed in profile view",
    "a black person photographed from the front",
    "a white person photographed from three-quarter angle",
    "portrait of a black person in a photography studio",
    "portrait of a white person under spotlight",
    "portrait of a black person sitting in a chair",
    "portrait of a white person standing in a studio",
    "portrait of a black person with symmetrical composition",
    "portrait of a white person with centered framing",
    "portrait of a black person with natural composition",
    "photo of a white person captured on 35mm film",
    "photo of a black person with lens flare",
    "portrait of a white person in soft pastel tones",
    "portrait of a black person in vibrant tones",
    "portrait of a white person in muted tones",
    "portrait of a black person with high contrast lighting",
    "portrait of a white person with low contrast lighting",
    "portrait of a black person in realistic style",
    "portrait of a white person in artistic style",
    "portrait of a black person taken with DSLR camera",
    "portrait of a white person taken with smartphone camera",
    "photo of a black person with detailed skin texture",
    "photo of a white person in a professional setting",
    "photo of a black person in a casual setting",
    "portrait of a white person with modern photography style",
    "portrait of a black person with classic portrait style",
]

white_asian_race_prompts_specific_v2 = [
    "a face of a white person",
    "a portrait of an asian person",
    "photo of a white person",
    "portrait photo of an asian person",
    "a close-up face of a white person",
    "a close-up photo of an asian person",
    "a detailed portrait of a white person",
    "studio photo of an asian person",
    "studio portrait of a white person",
    "professional photo of an asian person",
    "professional headshot of a white person",
    "a headshot of an asian person",
    "a professional studio headshot of a white person",
    "portrait of an asian person in natural light",
    "portrait of a white person indoors",
    "portrait of an asian person outdoors",
    "a white person facing the camera",
    "an asian person looking away from the camera",
    "a photo of a white person with neutral expression",
    "a portrait of a smiling asian person",
    "a portrait of a serious white person",
    "a portrait of an asian person with soft lighting",
    "a portrait of a white person with harsh lighting",
    "a photo of an asian person with blurred background",
    "a close-up portrait of a white person against a plain background",
    "an asian person with short hair",
    "a white person with long hair",
    "an asian person wearing casual clothes",
    "a white person wearing formal clothes",
    "a photo of an asian person in front of a plain wall",
    "a photo of a white person in front of a window",
    "an asian person sitting for a portrait",
    "a white person standing for a portrait",
    "portrait of an asian person with side lighting",
    "portrait of a white person with front lighting",
    "portrait of an asian person with back lighting",
    "portrait of a white person in studio lighting",
    "a high-resolution portrait of an asian person",
    "a close-up of a white person with shallow depth of field",
    "a photo of an asian person taken with soft focus",
    "portrait of a white person wearing a neutral-colored shirt",
    "portrait of an asian person with dark background",
    "portrait of a white person with light background",
    "portrait of an asian person in black and white",
    "black and white photo of a white person",
    "color photo of an asian person",
    "film photo of a white person",
    "digital photo of an asian person",
    "high quality photo of a white person",
    "a natural portrait of an asian person",
    "a candid portrait of a white person",
    "a posed portrait of an asian person",
    "a face of a white person",
    "a photo of an asian person",
    "a portrait of a white person",
    "a headshot of an asian person",
    "a portrait of a white person with neutral background",
    "a portrait of an asian person with colored background",
    "portrait of a white person with gradient background",
    "portrait of an asian person under daylight",
    "portrait of a white person under warm light",
    "portrait of an asian person under cold light",
    "a photo of a white person in front of a building",
    "a photo of an asian person in a room",
    "a portrait of a white person taken with natural sunlight",
    "portrait of an asian person with shallow depth of field",
    "photo of a white person with blurred city background",
    "portrait of an asian person with artistic lighting",
    "portrait of a white person taken outdoors at sunset",
    "portrait of an asian person taken indoors with flash",
    "a photo of a white person against a white wall",
    "a photo of an asian person against a dark wall",
    "a close-up portrait of a white person with soft shadows",
    "portrait of an asian person against a colorful background",
    "portrait of a white person in minimalistic style",
    "portrait of an asian person in cinematic lighting",
    "a white person photographed in profile view",
    "an asian person photographed from the front",
    "a white person photographed from three-quarter angle",
    "portrait of an asian person in a photography studio",
    "portrait of a white person under spotlight",
    "portrait of an asian person sitting in a chair",
    "portrait of a white person standing in a studio",
    "portrait of an asian person with symmetrical composition",
    "portrait of a white person with centered framing",
    "portrait of an asian person with natural composition",
    "photo of a white person captured on 35mm film",
    "photo of an asian person with lens flare",
    "portrait of a white person in soft pastel tones",
    "portrait of an asian person in vibrant tones",
    "portrait of a white person in muted tones",
    "portrait of an asian person with high contrast lighting",
    "portrait of a white person with low contrast lighting",
    "portrait of an asian person in realistic style",
    "portrait of a white person in artistic style",
    "portrait of an asian person taken with DSLR camera",
    "portrait of a white person taken with smartphone camera",
    "photo of an asian person with detailed skin texture",
    "photo of a white person in a professional setting",
    "photo of an asian person in a casual setting",
    "portrait of a white person with modern photography style",
    "portrait of an asian person with classic portrait style",
]

white_indian_race_prompts_specific_v2 = [
    "a face of a white person",
    "a portrait of an indian person",
    "photo of a white person",
    "portrait photo of an indian person",
    "a close-up face of a white person",
    "a close-up photo of an indian person",
    "a detailed portrait of a white person",
    "studio photo of an indian person",
    "studio portrait of a white person",
    "professional photo of an indian person",
    "professional headshot of a white person",
    "a headshot of an indian person",
    "a professional studio headshot of a white person",
    "portrait of an indian person in natural light",
    "portrait of a white person indoors",
    "portrait of an indian person outdoors",
    "a white person facing the camera",
    "an indian person looking away from the camera",
    "a photo of a white person with neutral expression",
    "a portrait of a smiling indian person",
    "a portrait of a serious white person",
    "a portrait of an indian person with soft lighting",
    "a portrait of a white person with harsh lighting",
    "a photo of an indian person with blurred background",
    "a close-up portrait of a white person against a plain background",
    "an indian person with short hair",
    "a white person with long hair",
    "an indian person wearing casual clothes",
    "a white person wearing formal clothes",
    "a photo of an indian person in front of a plain wall",
    "a photo of a white person in front of a window",
    "an indian person sitting for a portrait",
    "a white person standing for a portrait",
    "portrait of an indian person with side lighting",
    "portrait of a white person with front lighting",
    "portrait of an indian person with back lighting",
    "portrait of a white person in studio lighting",
    "a high-resolution portrait of an indian person",
    "a close-up of a white person with shallow depth of field",
    "a photo of an indian person taken with soft focus",
    "portrait of a white person wearing a neutral-colored shirt",
    "portrait of an indian person with dark background",
    "portrait of a white person with light background",
    "portrait of an indian person in black and white",
    "black and white photo of a white person",
    "color photo of an indian person",
    "film photo of a white person",
    "digital photo of an indian person",
    "high quality photo of a white person",
    "a natural portrait of an indian person",
    "a candid portrait of a white person",
    "a posed portrait of an indian person",
    "a face of a white person",
    "a photo of an indian person",
    "a portrait of a white person",
    "a headshot of an indian person",
    "a portrait of a white person with neutral background",
    "a portrait of an indian person with colored background",
    "portrait of a white person with gradient background",
    "portrait of an indian person under daylight",
    "portrait of a white person under warm light",
    "portrait of an indian person under cold light",
    "a photo of a white person in front of a building",
    "a photo of an indian person in a room",
    "a portrait of a white person taken with natural sunlight",
    "portrait of an indian person with shallow depth of field",
    "photo of a white person with blurred city background",
    "portrait of an indian person with artistic lighting",
    "portrait of a white person taken outdoors at sunset",
    "portrait of an indian person taken indoors with flash",
    "a photo of a white person against a white wall",
    "a photo of an indian person against a dark wall",
    "a close-up portrait of a white person with soft shadows",
    "portrait of an indian person against a colorful background",
    "portrait of a white person in minimalistic style",
    "portrait of an indian person in cinematic lighting",
    "a white person photographed in profile view",
    "an indian person photographed from the front",
    "a white person photographed from three-quarter angle",
    "portrait of an indian person in a photography studio",
    "portrait of a white person under spotlight",
    "portrait of an indian person sitting in a chair",
    "portrait of a white person standing in a studio",
    "portrait of an indian person with symmetrical composition",
    "portrait of a white person with centered framing",
    "portrait of an indian person with natural composition",
    "photo of a white person captured on 35mm film",
    "photo of an indian person with lens flare",
    "portrait of a white person in soft pastel tones",
    "portrait of an indian person in vibrant tones",
    "portrait of a white person in muted tones",
    "portrait of an indian person with high contrast lighting",
    "portrait of a white person with low contrast lighting",
    "portrait of an indian person in realistic style",
    "portrait of a white person in artistic style",
    "portrait of an indian person taken with DSLR camera",
    "portrait of a white person taken with smartphone camera",
    "photo of an indian person with detailed skin texture",
    "photo of a white person in a professional setting",
    "photo of an indian person in a casual setting",
    "portrait of a white person with modern photography style",
    "portrait of an indian person with classic portrait style",
]


direct_prompts_white_black = [
    # White person
    "a close-up showing the face of a white person with natural lighting",
    "studio headshot of a white man in formal clothes",
    "an image capturing a white woman smiling softly",
    "the face of a fair-skinned person with gentle expression",
    "a candid outdoor photo of a white person",
    "white gentleman sitting in warm afternoon light",
    "detailed portrait of a white person with freckles",
    "the profile of a white lady with blonde hair",
    "a relaxed photo of a white person laughing",
    "studio image of a white person against neutral backdrop",
    "smiling face of a white person under soft light",
    "professional headshot of a Caucasian individual",
    "a white man photographed in natural daylight",
    "photo showing a white person’s clear skin and calm look",
    "studio shot of a white lady with elegant hairstyle",
    "a photo taken outdoors of a white person with brown hair",
    "the detailed face of a white person with blue eyes",
    "a candid image of a white person in casual clothes",
    "headshot showing gentle smile of a fair-skinned person",
    "a white person leaning toward camera with soft smile",
    "an artistic photo of a white person in black and white",
    "studio close-up highlighting the features of a white person",
    "natural-light photo showing a white person’s relaxed face",
    "a calm expression of a Caucasian man in warm tones",
    "the white lady’s face captured in soft morning light",
    "close-up of a white person’s face in shadow and glow contrast",
    "a white person sitting indoors under window light",
    "detailed shot of a white person’s face with neutral mood",
    "the side profile of a white person with focused gaze",
    "a fair-skinned person smiling gently toward the camera",
    "candid outdoor portrait of a white person laughing",
    "white person resting their chin on their hand in thought",
    "a gentle photo of a white person with subtle lighting",
    "portrait showing natural beauty of a white person",
    "image capturing calm mood of a Caucasian individual",
    "a close view of a white person’s face with smooth skin",
    "studio composition of a white person with serious look",
    "a creative photo of a white person with soft pastel tones",
    "white person facing sideways with composed expression",
    "headshot with clean background featuring a fair-skinned person",
    "the face of a white person under balanced lighting",
    "photo of a white person smiling confidently indoors",
    "a natural outdoor portrait of a white individual",
    "artistic headshot showing fine features of a white person",
    "a photo capturing a white person’s gentle expression",
    "studio-lit image of a white person in casual clothing",
    "the face of a Caucasian person under bright daylight",
    "portrait showing warmth and softness of a white person",
    "photo taken outdoors featuring a white person’s face",
    "white person captured in calm natural light",

    # Black person
    "a close-up of a black person’s expressive face under soft light",
    "studio portrait of a dark-skinned gentleman with calm look",
    "an outdoor image of a black woman smiling naturally",
    "the face of a dark-skinned person glowing in daylight",
    "photo showing an African person’s confident expression",
    "black lady with curly hair looking directly at camera",
    "portrait capturing warm smile of a black person",
    "candid photo of an African-American person laughing",
    "studio headshot of a dark-skinned man in elegant outfit",
    "an image showing fine texture of a black person’s skin",
    "black person leaning against a neutral background",
    "portrait under warm lighting revealing dark skin tones",
    "photo showing a black person’s natural curly hairstyle",
    "the face of an African person in gentle light contrast",
    "a smiling black man outdoors during sunset",
    "photo of a black lady with expressive eyes",
    "portrait taken in soft morning light of a black person",
    "black person’s face framed by natural background",
    "studio capture of a black person with confident pose",
    "photo of a dark-skinned person under studio lighting",
    "artistic close-up emphasizing features of a black person",
    "black person in casual clothes smiling toward camera",
    "portrait highlighting rich tones of a dark-skinned person",
    "photo taken outdoors of a black person in warm glow",
    "face of a black person with smooth dark skin in detail",
    "a side profile of a black person with elegant posture",
    "black person laughing freely in natural daylight",
    "photo focusing on a black person’s confident gaze",
    "studio photo of a black person wearing bright colors",
    "portrait of a black woman with braided hair and jewelry",
    "photo of an African-American person with short hair",
    "a black person looking calm under neutral lighting",
    "portrait showing natural grace of a dark-skinned person",
    "photo of a black person sitting outdoors under sun",
    "headshot showing radiant smile of a black person",
    "black person facing camera with relaxed shoulders",
    "portrait of an African individual in thoughtful pose",
    "photo of a black person with detailed shadow play",
    "studio photo with deep contrast on black person’s features",
    "photo of a dark-skinned person in warm indoor light",
    "black person captured mid-laughter in daylight",
    "portrait of a black person with kind and open look",
    "a black person wearing elegant white clothes in studio",
    "close-up showing soft smile of a dark-skinned individual",
    "photo taken in nature with black person facing the sun",
    "artistic monochrome photo of a black person’s face",
    "black person under focused light with subtle expression",
    "portrait showing strength and calm in a black person",
    "candid photo of a black person with natural look",
    "close-up showing fine detail of dark skin under glow"
]


direct_prompts_white_asian = [
    # White person
    "a close-up showing the face of a white person with natural lighting",
    "studio headshot of a white man in formal clothes",
    "an image capturing a white woman smiling softly",
    "the face of a fair-skinned person with gentle expression",
    "a candid outdoor photo of a white person",
    "white gentleman sitting in warm afternoon light",
    "detailed portrait of a white person with freckles",
    "the profile of a white lady with blonde hair",
    "a relaxed photo of a white person laughing",
    "studio image of a white person against neutral backdrop",
    "smiling face of a white person under soft light",
    "professional headshot of a Caucasian individual",
    "a white man photographed in natural daylight",
    "photo showing a white person’s clear skin and calm look",
    "studio shot of a white lady with elegant hairstyle",
    "a photo taken outdoors of a white person with brown hair",
    "the detailed face of a white person with blue eyes",
    "a candid image of a white person in casual clothes",
    "headshot showing gentle smile of a fair-skinned person",
    "a white person leaning toward camera with soft smile",
    "an artistic photo of a white person in black and white",
    "studio close-up highlighting the features of a white person",
    "natural-light photo showing a white person’s relaxed face",
    "a calm expression of a Caucasian man in warm tones",
    "the white lady’s face captured in soft morning light",
    "close-up of a white person’s face in shadow and glow contrast",
    "a white person sitting indoors under window light",
    "detailed shot of a white person’s face with neutral mood",
    "the side profile of a white person with focused gaze",
    "a fair-skinned person smiling gently toward the camera",
    "candid outdoor portrait of a white person laughing",
    "white person resting their chin on their hand in thought",
    "a gentle photo of a white person with subtle lighting",
    "portrait showing natural beauty of a white person",
    "image capturing calm mood of a Caucasian individual",
    "a close view of a white person’s face with smooth skin",
    "studio composition of a white person with serious look",
    "a creative photo of a white person with soft pastel tones",
    "white person facing sideways with composed expression",
    "headshot with clean background featuring a fair-skinned person",
    "the face of a white person under balanced lighting",
    "photo of a white person smiling confidently indoors",
    "a natural outdoor portrait of a white individual",
    "artistic headshot showing fine features of a white person",
    "a photo capturing a white person’s gentle expression",
    "studio-lit image of a white person in casual clothing",
    "the face of a Caucasian person under bright daylight",
    "portrait showing warmth and softness of a white person",
    "photo taken outdoors featuring a white person’s face",
    "white person captured in calm natural light",

    # Asian person
    "a close-up of an Asian person’s calm face under soft lighting",
    "studio portrait of an East Asian woman with natural look",
    "photo of an Asian man wearing glasses and smiling gently",
    "the face of an East Asian person with smooth skin tone",
    "a candid outdoor image of an Asian person in daylight",
    "photo showing a Japanese man with thoughtful expression",
    "portrait of an Asian woman with black hair and warm smile",
    "studio headshot of an East Asian person against grey background",
    "photo of a Korean person in natural light with soft background",
    "detailed close-up of an Asian person’s expressive eyes",
    "portrait capturing calm mood of an Asian individual",
    "an image of an Asian man dressed in formal clothes",
    "photo showing natural features of an East Asian woman",
    "portrait in daylight highlighting warm tone of Asian skin",
    "a serene photo of an Asian person with gentle smile",
    "studio shot of an Asian person in neutral color outfit",
    "photo of an Asian person outdoors during golden hour",
    "portrait of a Chinese person looking directly at camera",
    "candid image of an Asian woman laughing softly",
    "headshot of a dark-haired Asian person in soft light",
    "a photo showing the delicate features of an Asian individual",
    "portrait with balanced light showing Asian person’s face",
    "close-up photo of an Asian person with peaceful expression",
    "an outdoor photo of an Asian man under morning light",
    "studio capture of an Asian person with calm look",
    "a side profile of an Asian woman with straight black hair",
    "photo showing natural expression of a Japanese person",
    "portrait of a Korean person in soft indoor lighting",
    "artistic black-and-white image of an Asian person",
    "photo of an Asian person with elegant posture",
    "portrait highlighting the symmetry of an Asian person’s face",
    "an image showing relaxed mood of an East Asian person",
    "studio photo of an Asian person with friendly smile",
    "portrait showing kindness and calmness of a Chinese person",
    "photo of an Asian person standing near a window",
    "close-up of a Japanese person’s face in balanced tones",
    "a candid shot of an Asian woman laughing outdoors",
    "portrait of a Korean man with soft shadow contrast",
    "photo of an Asian person with smooth complexion and glow",
    "portrait showing confidence of a young Asian person",
    "studio image of an Asian person in clean white background",
    "photo of an Asian person facing the sunlight naturally",
    "headshot with artistic framing of an East Asian face",
    "portrait of an Asian person wearing light-colored shirt",
    "an image of an Asian individual in warm evening light",
    "photo of a calm Asian person with neutral expression",
    "portrait of an East Asian woman with elegant posture",
    "photo showing the profile of an Asian person in studio",
    "artistic portrait of an Asian person in subtle tones",
    "a serene image of an Asian person smiling gently",
    "photo capturing warmth and peace in an Asian person’s face"
]


direct_prompts_white_indian = [
    # White person
    "a close-up showing the face of a white person with natural lighting",
    "studio headshot of a white man in formal clothes",
    "an image capturing a white woman smiling softly",
    "the face of a fair-skinned person with gentle expression",
    "a candid outdoor photo of a white person",
    "white gentleman sitting in warm afternoon light",
    "detailed portrait of a white person with freckles",
    "the profile of a white lady with blonde hair",
    "a relaxed photo of a white person laughing",
    "studio image of a white person against neutral backdrop",
    "smiling face of a white person under soft light",
    "professional headshot of a Caucasian individual",
    "a white man photographed in natural daylight",
    "photo showing a white person’s clear skin and calm look",
    "studio shot of a white lady with elegant hairstyle",
    "a photo taken outdoors of a white person with brown hair",
    "the detailed face of a white person with blue eyes",
    "a candid image of a white person in casual clothes",
    "headshot showing gentle smile of a fair-skinned person",
    "a white person leaning toward camera with soft smile",
    "an artistic photo of a white person in black and white",
    "studio close-up highlighting the features of a white person",
    "natural-light photo showing a white person’s relaxed face",
    "a calm expression of a Caucasian man in warm tones",
    "the white lady’s face captured in soft morning light",
    "close-up of a white person’s face in shadow and glow contrast",
    "a white person sitting indoors under window light",
    "detailed shot of a white person’s face with neutral mood",
    "the side profile of a white person with focused gaze",
    "a fair-skinned person smiling gently toward the camera",
    "candid outdoor portrait of a white person laughing",
    "white person resting their chin on their hand in thought",
    "a gentle photo of a white person with subtle lighting",
    "portrait showing natural beauty of a white person",
    "image capturing calm mood of a Caucasian individual",
    "a close view of a white person’s face with smooth skin",
    "studio composition of a white person with serious look",
    "a creative photo of a white person with soft pastel tones",
    "white person facing sideways with composed expression",
    "headshot with clean background featuring a fair-skinned person",
    "the face of a white person under balanced lighting",
    "photo of a white person smiling confidently indoors",
    "a natural outdoor portrait of a white individual",
    "artistic headshot showing fine features of a white person",
    "a photo capturing a white person’s gentle expression",
    "studio-lit image of a white person in casual clothing",
    "the face of a Caucasian person under bright daylight",
    "portrait showing warmth and softness of a white person",
    "photo taken outdoors featuring a white person’s face",
    "white person captured in calm natural light",

    # Indian person
    "a close-up of an Indian person’s face under warm sunlight",
    "studio portrait of an Indian woman with traditional jewelry",
    "photo of an Indian man smiling naturally in daylight",
    "the face of an Indian person with calm expression",
    "a candid outdoor image of an Indian person under soft light",
    "portrait of an Indian man wearing formal attire",
    "photo showing natural beauty of an Indian woman",
    "studio headshot of an Indian person with confident look",
    "a detailed photo of an Indian person with expressive eyes",
    "portrait highlighting warm brown skin tones of an Indian person",
    "photo taken outdoors of an Indian woman with dark hair",
    "a serene image of an Indian man with soft smile",
    "portrait of an Indian person in natural light setting",
    "photo showing traditional elegance of an Indian lady",
    "close-up of an Indian person with peaceful expression",
    "portrait taken during golden hour of an Indian person",
    "studio image showing clear features of an Indian person",
    "a calm photo of an Indian person looking to the side",
    "headshot showing natural smile of an Indian individual",
    "portrait of an Indian woman with bright outfit and jewelry",
    "photo of an Indian man in professional clothing indoors",
    "a detailed close-up of an Indian person’s face texture",
    "portrait showing an Indian person’s gentle expression",
    "photo capturing a smiling Indian person in warm light",
    "studio shot of an Indian person with traditional look",
    "photo of an Indian person standing near a bright window",
    "portrait of an Indian man under balanced lighting",
    "an artistic image of an Indian person in soft color tones",
    "photo showing calm mood of an Indian woman in sari",
    "portrait with natural lighting of an Indian individual",
    "an image of an Indian person smiling with kind eyes",
    "photo capturing elegance of a dark-haired Indian woman",
    "studio portrait of an Indian person with neutral expression",
    "photo showing confidence of an Indian man looking forward",
    "portrait of an Indian person with warm tone contrast",
    "a candid image of an Indian person laughing gently",
    "photo of an Indian person outdoors in morning light",
    "studio headshot showing detailed features of an Indian person",
    "portrait taken under soft indoor light of an Indian person",
    "a calm and composed photo of an Indian person",
    "photo showing subtle smile of an Indian individual",
    "portrait of an Indian woman with long dark hair",
    "photo of an Indian person sitting in natural light",
    "studio image of an Indian man with friendly expression",
    "portrait showing beauty and grace of an Indian person",
    "photo taken outdoors of an Indian person with serene look",
    "portrait showing rich warm tones of an Indian person’s skin",
    "a candid photo of an Indian person with joyful mood",
    "portrait showing expressive face of an Indian individual",
    "photo of an Indian person captured under gentle lighting",
    "portrait showing confidence and warmth of an Indian person"
]

direct_prompts_young_old = [
    # Young (to 19 y.o.)
    "portrait of a young person",
    "close-up of a teenage face",
    "detailed photo of a child smiling",
    "headshot of a young teenager",
    "studio portrait of a 10-year-old",
    "close-up of a happy kid’s face",
    "photo of a young boy outdoors",
    "photo of a young girl outdoors",
    "face of a cheerful school student",
    "portrait of a child looking at the camera",
    "photo of a young person wearing a hoodie",
    "photo of a teenager with bright expression",
    "detailed portrait of a young face with soft lighting",
    "face of a playful child",
    "photo of a young person in natural light",
    "portrait of a 12-year-old person",
    "close-up of a smiling young person",
    "photo of a kid with freckles",
    "portrait of a young person with short hair",
    "photo of a teenager with long hair",
    "close-up of a young face with gentle expression",
    "photo of a student with a backpack",
    "portrait of a child with curly hair",
    "studio headshot of a young person",
    "smiling face of a young person",
    "serious portrait of a young teenager",
    "artistic portrait of a child",
    "photo of a child playing outdoors",
    "portrait of a kid against a plain background",
    "close-up of a young person in soft lighting",
    "detailed headshot of a teenager",
    "portrait of a cheerful school-aged person",
    "face of a young person with natural look",
    "profile portrait of a young person",
    "young person looking slightly away from camera",
    "photo of a kid in casual clothes",
    "photo of a young person with smooth skin",
    "portrait of a 16-year-old person",
    "smiling portrait of a young person",
    "photo of a young person with youthful features",
    "portrait of a teenager sitting indoors",
    "young person photographed against pastel background",
    "face of a child with soft expression",
    "close-up of a student’s face",
    "detailed portrait of a youthful person",
    "candid portrait of a young person laughing",
    "artistic headshot of a young person",
    "portrait of a young person with light background",
    "photo of a kid with natural lighting",
    "photo of a young person with joyful look",

    # Old (elderly)
    "portrait of an elderly person",
    "close-up of an old person’s face",
    "detailed portrait of a senior citizen",
    "face of an old person with wrinkles",
    "studio headshot of an elderly individual",
    "portrait of an old man smiling",
    "portrait of an old woman smiling",
    "photo of a senior person in natural light",
    "detailed face of a wise-looking elderly person",
    "portrait of an old person with grey hair",
    "close-up of an old person’s eyes and face",
    "photo of an elderly person wearing glasses",
    "portrait of a senior person with soft lighting",
    "headshot of a person with visible wrinkles",
    "close-up of an elderly person looking serious",
    "artistic portrait of an old person",
    "photo of an old person with white hair",
    "detailed photo of a senior person smiling gently",
    "portrait of an elderly person outdoors",
    "close-up of a wrinkled face in sunlight",
    "face of an old person showing age lines",
    "portrait of a person over 70 years old",
    "senior person photographed against plain background",
    "candid portrait of an elderly person laughing",
    "old person looking directly at the camera",
    "detailed portrait of a person with age marks",
    "elderly person with expressive eyes",
    "portrait of an old person in warm lighting",
    "close-up photo of a senior citizen",
    "portrait of a person with silver hair",
    "photo of an old person indoors",
    "portrait of an aged person wearing a hat",
    "photo of an elderly person with kind expression",
    "black and white photo of an old person’s face",
    "close-up of a smiling elderly person",
    "portrait of an old person with deep wrinkles",
    "senior person looking off to the side",
    "detailed portrait of a person with grey beard",
    "photo of an old person sitting outdoors",
    "portrait of a wrinkled face with natural light",
    "close-up portrait of an old woman",
    "close-up portrait of an old man",
    "photo of an elderly person against neutral background",
    "portrait of an old person with soft focus",
    "artistic black-and-white portrait of a senior",
    "portrait of a thoughtful old person",
    "close-up of a face showing signs of aging",
    "portrait of a smiling elderly person indoors",
    "senior person with glasses and gentle expression",
    "portrait of an aged person under warm light"
]
